### PR TITLE
Update Dockerfiles

### LINKED ISSUE #42: node_modules directory not created using dockerfile example. No error messages
I'm using your dockerfile as suggested on https://hub.docker.com/r/keymetrics/pm2/ but there is no node_modules directory created.

my docker version is  17.09.0-ce, build afdb6d4

Below is the output of the docker build command. As you can see there is no node_modules so the javascript program will fail with module xxx not found.

When I run the container interactively (first installing a bash shell with RUN apk add --no-cache bash in the dockerfile) and run NPM install, it will install the dependencies in the /app folder without errors.

I don't know how to solve this. I hope somebody sess what I'm doing wrong.
Thanks.

_Output of docker build:_

```
Step 7/12 : ENV NPM_CONFIG_LOGLEVEL warn
 ---> Using cache
 ---> 9fdec208e92e
Step 8/12 : RUN npm install
 ---> Running in 0c0912ab16e5
added 355 packages in 24.476s
 ---> 57ed4e10162e
Removing intermediate container 0c0912ab16e5
Step 9/12 : RUN ls -al -R
 ---> Running in b05074ef2642
.:
total 20
drwxr-xr-x    3 root     root          4096 Nov  6 08:16 .
drwxr-xr-x   51 root     root          4096 Nov  6 08:16 ..
drwxr-xr-x    4 root     root          4096 Nov  6 08:14 app
-rw-r--r--    1 root     root          1540 Nov  6 05:14 package.json
-rw-r--r--    1 root     root           179 Nov  6 05:03 pm2.json
```

_My dockerfile:_

```
FROM keymetrics/pm2:8

# Bundle APP files
COPY app app/
COPY package.json .
COPY pm2.json .

# Install bash shell
# RUN apk add --no-cache bash

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production

# Show current folder structure in logs
RUN ls -al -R

# Expose ports
EXPOSE 80 443 3333 43554

CMD [ "pm2-docker", "start", "pm2.json" ]
```
_My package.json file:_

```
{
  "name": "microservices",
  "version": "1.0.10",
  "description": "Broker microservice for cloud trader",
  "repository": {
    "type": "git",
    "url": "git+https://gitlab.com/edelacruz/cloudtrader-microservices"
  },
  "main": "index.js",
  "scripts": {
    "start": "pm2 start process.yml",
    "prestart": "pm2 stop process.yml && pm2 delete process.yml",
    "stop": "pm2 stop process.yml && pm2 delete process.yml",
    "test": "mocha ./test",
    "version:patch": "npm version patch -m 'Upgrade to %s'",
    "version:release": "npm version major",
    "push": "npm run version:patch && git push --tags origin master",
    "build": "npm test && npm run push",
    "docker-build": "docker build -t cloudtrader/microservices:latest .",
    "docker-run": "docker run --name micro -p 3333:3333 --net host cloudtrader/microservices:latest"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "async": "^2.5.0",
    "debug": "^2.6.9",
    "ioredis": "^3.2.1",
    "jsonwebtoken": "^7.4.3",
    "mongodb": "^2.2.33",
    "querystring": "^0.2.0",
    "socket.io-client": "^2.0.4",
    "winston": "^2.4.0",
    "winston-loggly-bulk": "^2.0.1",
    "ws": "^3.2.0"
  },
  "devDependencies": {
    "chai": "^4.0.2",
    "chai-as-promised": "^7.1.1",
    "mocha": "^3.4.2",
    "standard": "^10.0.3"
  },
  "standard": {
    "env": [
      "mocha",
      "chai"
    ],
    "globals": [
      "describe",
      "context",
      "before",
      "beforeEach",
      "after",
      "afterEach",
      "it",
      "expect"
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by simonepri**
# Changes
- [x] Move all Dockerfiles into a folder called tags to keep things a bit more clean.
- [x] Remove support for non LTS versions like told in https://github.com/keymetrics/docker-pm2/issues/25#issuecomment-324335327
- [x] Fix #42
- [x] Add more images like told in https://github.com/keymetrics/docker-pm2/issues/25#issuecomment-322684179
- [x] Update available tags in the readme

> Before merging this we must change the building config on the Docker Hub!

### CODE REVIEW

**Comment by simonepri** [comment]
The update readme is previewable [here](https://github.com/keymetrics/docker-pm2/blob/b2807b99fd64f3a4e9b878365857857213c3de8b/README.md).

**Comment by simonepri** [comment]
@Unitech the names of the new tags does not conflict with the ones already published on the Docker Hub.
In this way it should be safe to publish them without causing problems to user.

We just need to remove the old tags from the auto-build (keeping the images already built) and add the new ones that have different names. _(I'm not able to access to the Docker Hub settings anymore so you have to do it on your side)_

**Comment by Unitech** [comment]
image

Does that look good to you?

**Comment by Unitech** [comment]
By the way that is a really great job 👍

**Comment by simonepri** [comment]
The DockerFile locations are changed:
https://github.com/keymetrics/docker-pm2/tree/master/tags

**Comment by Unitech** [comment]
done 
image

**Comment by simonepri** [comment]
Dockerfile Location | Docker Tag Name
---|---
/tags/latest/alpine/|latest-alpine
/tags/8/alpine/|8-alpine
/tags/6/alpine/|6-alpine
/tags/4/alpine/|4-alpine
**Dockerfile Location** | **Docker Tag Name**
/tags/latest/stretch/|latest-stretch
/tags/8/stretch/|8-stretch
/tags/6/stretch/|6-stretch
/tags/4/stretch/|4-stretch
**Dockerfile Location** | **Docker Tag Name**
/tags/latest/jessie/|latest-jessie
/tags/8/jessie/|8-jessie
/tags/6/jessie/|6-jessie
/tags/4/jessie/|4-jessie
**Dockerfile Location** | **Docker Tag Name**
/tags/latest/slim/|latest-slim
/tags/8/slim/|8-slim
/tags/6/slim/|6-slim
/tags/4/slim/|4-slim
**Dockerfile Location** | **Docker Tag Name**
/tags/latest/wheezy/|latest-wheezy
/tags/8/wheezy/|8-wheezy
/tags/6/wheezy/|6-wheezy
/tags/4/wheezy/|4-wheezy

**Comment by Unitech** [comment]
olright! I just did it

I also gave you full perm on the repo on the docker hub

**Comment by simonepri** [comment]
Anyway node is dropping wheezy support in the near feature:
https://github.com/nodejs/docker-node/pull/567

So I think as soon they remove it we can to do the same.
I think that it's convenient for us to follow their same tags structure.

**Pull request merged**
